/** @format */

module.exports = {
	products: [
		{
			_id: "1",
			name: " Balance",
			Categories: "shoe",
			image: "/Images/pic1.jpeg",
			prices: 97,
			brand: "New Balance",
			rating: 3.9,
			reviews: 7,
			countInStock: 20,
		},
		{
			_id: "2",
			name: " Airmax",
			Categories: "shoe",
			image: "/Images/pic2.jpeg",
			prices: 297,
			brand: "Nike",
			rating: 4.9,
			reviews: 27,
			countInStock: 20,
		},
		{
			_id: "3",
			name: " jogger",
			Categories: "pants",
			image: "/Images/pant1.jpeg",
			prices: 56,
			brand: "Jordan",
			rating: 4.0,
			reviews: 10,
			countInStock: 80,
		},
		{
			_id: "4",
			name: " westbrook",
			Categories: "pants",
			image: "/Images/pant2.jpeg",
			prices: 497,
			brand: "True religion",
			rating: 7.9,
			reviews: 56,
			countInStock: 15,
		},
	],
};
